name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Publish to NPM
        run: yarn publish --access=public
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}